name: deploy

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Hugo
      env:
        HUGO_VERSION: 0.117.0
      run: |
        mkdir ~/hugo
        cd ~/hugo
        curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
        tar -xvzf hugo.tar.gz
        sudo mv hugo /usr/local/bin
    - name: Run Hugo
      run: hugo --gc --minify --verbose
    - name: Install rclone
      run: sudo apt install rclone -y
    - name: Create SSH Key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.PRIVATE_SSH_KEY}}
    - name: Sync with remote
      run: |
        eval `ssh-agent`
        ssh-add
        rclone sync public/ remote:${REMOTE_DIR} --exclude-from .rcloneignore
      env:
        RCLONE_CONFIG_REMOTE_TYPE: sftp
        RCLONE_CONFIG_REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        RCLONE_CONFIG_REMOTE_USER: ${{secrets.REMOTE_USER}}
        REMOTE_DIR: ${{secrets.REMOTE_DIR}}
